"""Phase 0 exit criterion: one database smoke test that inserts and reads a conversation row.

Also checks the parts of the schema that are easy to get wrong silently: pgvector is
installed, JSONB round-trips, timestamps are timezone-aware, the generated tsvector column
works, and the per-test truncation actually happens.
"""

from datetime import UTC

from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession

from support_core.knowledge.embedding import DIMENSIONS as EMBEDDING_DIMENSIONS
from support_core.storage.models import Conversation, DocChunk, DocSource


async def test_insert_and_read_conversation(db_session: AsyncSession) -> None:
    conversation = Conversation(
        channel="web_chat",
        customer_ref="cust-42",
        context={"locale": "en-GB", "identity_verified": False},
    )
    db_session.add(conversation)
    await db_session.commit()

    assert conversation.id is not None, "primary key should be generated by Postgres"

    loaded = (
        await db_session.execute(select(Conversation).where(Conversation.id == conversation.id))
    ).scalar_one()
    assert loaded.channel == "web_chat"
    assert loaded.customer_ref == "cust-42"
    assert loaded.status == "open", "server default"
    assert loaded.context == {"locale": "en-GB", "identity_verified": False}
    assert loaded.summary is None
    assert loaded.closed_at is None
    assert loaded.created_at.tzinfo is not None, "timestamptz must come back timezone-aware"
    assert loaded.created_at.utcoffset() == UTC.utcoffset(None)


async def test_tables_are_truncated_between_tests(db_session: AsyncSession) -> None:
    """Runs after the insert test in file order; the row it created must be gone."""
    count = (await db_session.execute(select(func.count()).select_from(Conversation))).scalar_one()
    assert count == 0


async def test_pgvector_extension_is_installed(engine: AsyncEngine) -> None:
    async with engine.connect() as conn:
        row = await conn.execute(
            text("SELECT extversion FROM pg_extension WHERE extname = 'vector'")
        )
        assert row.scalar_one_or_none() is not None


DIMENSIONS = EMBEDDING_DIMENSIONS
"""``doc_chunk.embedding`` is ``vector(128)`` from migration ``0010`` on (phase-0 finding N12).

The number is imported rather than written out, because the point of fixing the dimension was
that two places can no longer disagree about it - and a test that hard-coded 128 would be a third
place."""

NEAR = [0.1, 0.2, 0.3] + [0.0] * (DIMENSIONS - 3)
FAR = [10.0, 10.0, 10.0] + [0.0] * (DIMENSIONS - 3)
PROBE = [0.1, 0.2, 0.31] + [0.0] * (DIMENSIONS - 3)


async def test_doc_chunk_embedding_and_tsvector(db_session: AsyncSession) -> None:
    source = DocSource(id="policy-docs", type="markdown_dir", version="v1")
    chunk = DocChunk(
        source_id="policy-docs",
        source_version="v1",
        chunk_index=0,
        locator="docs/refunds.md#processing-time",
        text="Refunds take 5 to 7 business days to reach the original payment method.",
        embedding=NEAR,
    )
    # No ORM relationship links the two models, so flush the parent first as ingestion will.
    db_session.add(source)
    await db_session.flush()
    db_session.add(chunk)
    await db_session.commit()

    matched = (
        (
            await db_session.execute(
                select(DocChunk.locator).where(
                    DocChunk.tsv.op("@@")(func.to_tsquery("english", "refund & days"))
                )
            )
        )
        .scalars()
        .all()
    )
    assert matched == ["docs/refunds.md#processing-time"]

    unmatched = (
        (
            await db_session.execute(
                select(DocChunk.id).where(
                    DocChunk.tsv.op("@@")(func.to_tsquery("english", "aeroplane"))
                )
            )
        )
        .scalars()
        .all()
    )
    assert unmatched == []

    stored = (
        await db_session.execute(select(DocChunk.embedding).where(DocChunk.chunk_index == 0))
    ).scalar_one()
    assert stored is not None
    assert [round(float(x), 6) for x in stored] == NEAR

    # Vector distance operators work through SQLAlchemy (phase 5's hybrid search needs this).
    far = DocChunk(
        source_id="policy-docs",
        source_version="v1",
        chunk_index=1,
        locator="docs/other.md#x",
        text="Unrelated.",
        embedding=FAR,
    )
    db_session.add(far)
    await db_session.commit()
    nearest = (
        (
            await db_session.execute(
                select(DocChunk.chunk_index).order_by(
                    DocChunk.embedding.l2_distance(PROBE)
                )
            )
        )
        .scalars()
        .all()
    )
    assert nearest == [0, 1]
